POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Wallace Wesley",
  "email": "wallace@test.com.br"
}

###

GET http://localhost:3333/invite/wallace123

###

GET http://localhost:3333/subscribers/wallace123/ranking/clicks