### Cadastro de usuario, com ou sem indicação

POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Usuario indicado 2",
  "email": "usuario.indicado2@test.com.br",
  "referrer": "651d3b29-03d9-414c-b6d4-c35ea89406cd"
}

### Link para invite a partir do ID do usuario

GET http://localhost:3333/invite/651d3b29-03d9-414c-b6d4-c35ea89406cd

### Ranking de clicks a partir do ID do usuario

GET http://localhost:3333/subscribers/651d3b29-03d9-414c-b6d4-c35ea89406cd/ranking/clicks

### Ranking de indicações a partir do ID do usuario que indicou

GET http://localhost:3333/subscribers/651d3b29-03d9-414c-b6d4-c35ea89406cd/ranking/count

### Posição do usuário no ranking a partir do ID

GET http://localhost:3333/subscribers/651d3b29-03d9-414c-b6d4-c35ea89406cd/ranking/position